const SUCCESS_CODE = 200;
const CREATED_CODE = 201;
// const INCORRECT_DATA_ERROR_CODE = 400; //
// const NOT_FOUND_ERROR_CODE = 404; //
// const SERVER_ERROR_CODE = 500; //
// const AUTHORIZATION_ERROR_CODE = 401; //

module.exports = {
  SUCCESS_CODE,
  CREATED_CODE,
  // INCORRECT_DATA_ERROR_CODE,
  // NOT_FOUND_ERROR_CODE,
  // SERVER_ERROR_CODE,
  // AUTHORIZATION_ERROR_CODE,
};
